"""initial schema

Revision ID: 15b90065fc36
Revises:
Create Date: 2026-02-23 21:48:02.820484

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15b90065fc36"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creators",
        sa.Column("comicvine_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("comicvine_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_creators_comicvine_id"), "creators", ["comicvine_id"], unique=True)
    op.create_index(op.f("ix_creators_name"), "creators", ["name"], unique=False)
    op.create_table(
        "download_client_configs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "client_type",
            sa.Enum("SABNZBD", "QBITTORRENT", name="downloadclienttype"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("download_dir", sa.String(length=1000), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_check_results",
        sa.Column("component", sa.String(length=100), nullable=False),
        sa.Column("check_name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("HEALTHY", "DEGRADED", "UNHEALTHY", "UNKNOWN", name="healthstatus"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("details_json", sa.Text(), nullable=True),
        sa.Column("response_time_ms", sa.Float(), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_health_check_component_time",
        "health_check_results",
        ["component", "checked_at"],
        unique=False,
    )
    op.create_table(
        "indexer_configs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "indexer_type",
            sa.Enum("NEWZNAB", "TORZNAB", "PROWLARR", name="indexertype"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("categories", sa.String(length=255), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("disabled_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capabilities_json", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "library_roots",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_scan_duration_seconds", sa.Float(), nullable=True),
        sa.Column("last_scan_files_found", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "publishers",
        sa.Column("comicvine_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_path", sa.String(length=500), nullable=True),
        sa.Column("comicvine_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_publishers_comicvine_id"), "publishers", ["comicvine_id"], unique=True)
    op.create_index(op.f("ix_publishers_name"), "publishers", ["name"], unique=False)
    op.create_table(
        "system_config",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "api_keys",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_table(
        "series",
        sa.Column("comicvine_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=False),
        sa.Column("year_start", sa.Integer(), nullable=True),
        sa.Column("year_end", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.Enum("CONTINUING", "ENDED", "UNKNOWN", name="seriesstatus"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cover_path", sa.String(length=500), nullable=True),
        sa.Column("issue_count", sa.Integer(), nullable=False),
        sa.Column("comicvine_url", sa.String(length=500), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column(
            "monitor_type",
            sa.Enum("ALL", "NEW_ONLY", "SPECIFIC", "MISSING", "NONE", name="monitortype"),
            nullable=False,
        ),
        sa.Column("monitor_range_start", sa.Float(), nullable=True),
        sa.Column("monitor_range_end", sa.Float(), nullable=True),
        sa.Column("metadata_last_refreshed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_source", sa.String(length=50), nullable=True),
        sa.Column("publisher_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["publisher_id"], ["publishers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_series_comicvine_id"), "series", ["comicvine_id"], unique=True)
    op.create_index(op.f("ix_series_monitored"), "series", ["monitored"], unique=False)
    op.create_index(op.f("ix_series_sort_title"), "series", ["sort_title"], unique=False)
    op.create_index(op.f("ix_series_title"), "series", ["title"], unique=False)
    op.create_index("ix_series_title_year", "series", ["title", "year_start"], unique=False)
    op.create_table(
        "story_arcs",
        sa.Column("comicvine_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("publisher_id", sa.Integer(), nullable=True),
        sa.Column("comicvine_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["publisher_id"], ["publishers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_story_arcs_comicvine_id"), "story_arcs", ["comicvine_id"], unique=True)
    op.create_index(op.f("ix_story_arcs_name"), "story_arcs", ["name"], unique=False)
    op.create_table(
        "issues",
        sa.Column("comicvine_id", sa.Integer(), nullable=True),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("issue_number", sa.Float(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("cover_path", sa.String(length=500), nullable=True),
        sa.Column("comicvine_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("UNKNOWN", "WANTED", "DOWNLOADING", "OWNED", "SKIPPED", name="issuestatus"),
            nullable=False,
        ),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("store_date", sa.Date(), nullable=True),
        sa.Column("metadata_source", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "issue_number", name="uq_series_issue"),
    )
    op.create_index(op.f("ix_issues_comicvine_id"), "issues", ["comicvine_id"], unique=True)
    op.create_index("ix_issues_release_date", "issues", ["release_date"], unique=False)
    op.create_index("ix_issues_status", "issues", ["status"], unique=False)
    op.create_table(
        "download_history",
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("indexer_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("download_url", sa.String(length=2000), nullable=False),
        sa.Column(
            "download_client",
            sa.Enum("SABNZBD", "QBITTORRENT", name="downloadclienttype"),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "SENT",
                "DOWNLOADING",
                "PAUSED",
                "COMPLETED",
                "FAILED",
                "POST_PROCESSING",
                "IMPORTED",
                name="downloadstate",
            ),
            nullable=False,
        ),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("downloaded_path", sa.String(length=1000), nullable=True),
        sa.Column("final_path", sa.String(length=1000), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["indexer_id"], ["indexer_configs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_download_history_issue", "download_history", ["issue_id"], unique=False)
    op.create_index("ix_download_history_state", "download_history", ["state"], unique=False)
    op.create_table(
        "issue_creators",
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["creators.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("issue_id", "creator_id"),
    )
    op.create_table(
        "issue_story_arcs",
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("story_arc_id", sa.Integer(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["story_arc_id"], ["story_arcs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("issue_id", "story_arc_id"),
    )
    op.create_table(
        "library_files",
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "file_format", sa.Enum("CBZ", "CBR", "CB7", "PDF", name="fileformat"), nullable=False
        ),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("file_modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "match_confidence",
            sa.Enum("HIGH", "MEDIUM", "LOW", "UNMATCHED", "MANUAL", name="matchconfidence"),
            nullable=False,
        ),
        sa.Column("parsed_series", sa.String(length=500), nullable=True),
        sa.Column("parsed_issue_number", sa.Float(), nullable=True),
        sa.Column("parsed_year", sa.Integer(), nullable=True),
        sa.Column("parsed_publisher", sa.String(length=255), nullable=True),
        sa.Column("has_comicinfo", sa.Boolean(), nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=True),
        sa.Column("library_root_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["library_root_id"], ["library_roots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_path"),
    )
    op.create_index("ix_library_files_match", "library_files", ["match_confidence"], unique=False)
    op.create_index("ix_library_files_path", "library_files", ["file_path"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_library_files_path", table_name="library_files")
    op.drop_index("ix_library_files_match", table_name="library_files")
    op.drop_table("library_files")
    op.drop_table("issue_story_arcs")
    op.drop_table("issue_creators")
    op.drop_index("ix_download_history_state", table_name="download_history")
    op.drop_index("ix_download_history_issue", table_name="download_history")
    op.drop_table("download_history")
    op.drop_index("ix_issues_status", table_name="issues")
    op.drop_index("ix_issues_release_date", table_name="issues")
    op.drop_index(op.f("ix_issues_comicvine_id"), table_name="issues")
    op.drop_table("issues")
    op.drop_index(op.f("ix_story_arcs_name"), table_name="story_arcs")
    op.drop_index(op.f("ix_story_arcs_comicvine_id"), table_name="story_arcs")
    op.drop_table("story_arcs")
    op.drop_index("ix_series_title_year", table_name="series")
    op.drop_index(op.f("ix_series_title"), table_name="series")
    op.drop_index(op.f("ix_series_sort_title"), table_name="series")
    op.drop_index(op.f("ix_series_monitored"), table_name="series")
    op.drop_index(op.f("ix_series_comicvine_id"), table_name="series")
    op.drop_table("series")
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_table("system_config")
    op.drop_index(op.f("ix_publishers_name"), table_name="publishers")
    op.drop_index(op.f("ix_publishers_comicvine_id"), table_name="publishers")
    op.drop_table("publishers")
    op.drop_table("library_roots")
    op.drop_table("indexer_configs")
    op.drop_index("ix_health_check_component_time", table_name="health_check_results")
    op.drop_table("health_check_results")
    op.drop_table("download_client_configs")
    op.drop_index(op.f("ix_creators_name"), table_name="creators")
    op.drop_index(op.f("ix_creators_comicvine_id"), table_name="creators")
    op.drop_table("creators")
    # ### end Alembic commands ###
