"""add import job tables

Revision ID: e17c92df151a
Revises: b7a3c5d9e1f2
Create Date: 2026-03-06 14:59:31.409308

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e17c92df151a"
down_revision: str | Sequence[str] | None = "b7a3c5d9e1f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_jobs",
        sa.Column("source_path", sa.String(length=1000), nullable=False),
        sa.Column(
            "source_type", sa.Enum("FILESYSTEM", "MYLAR3", name="importsourcetype"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SCANNING",
                "ANALYZING",
                "MATCHING",
                "REVIEW",
                "IMPORTING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="importjobstatus",
            ),
            nullable=False,
        ),
        sa.Column("scan_total_files", sa.Integer(), nullable=False),
        sa.Column("scan_total_dirs", sa.Integer(), nullable=False),
        sa.Column("series_found", sa.Integer(), nullable=False),
        sa.Column("series_duplicate", sa.Integer(), nullable=False),
        sa.Column("series_matched", sa.Integer(), nullable=False),
        sa.Column("series_no_match", sa.Integer(), nullable=False),
        sa.Column("series_new", sa.Integer(), nullable=False),
        sa.Column("series_imported", sa.Integer(), nullable=False),
        sa.Column("series_failed", sa.Integer(), nullable=False),
        sa.Column("scan_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scan_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("match_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("match_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("import_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("import_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("target_library_root_id", sa.Integer(), nullable=True),
        sa.Column("monitor_type", sa.String(length=50), nullable=False),
        sa.Column("search_on_add", sa.Boolean(), nullable=False),
        sa.Column("cv_match_threshold", sa.Float(), nullable=False),
        sa.Column("auto_accept_high_confidence", sa.Boolean(), nullable=False),
        sa.Column("skip_no_match", sa.Boolean(), nullable=False),
        sa.Column("mylar3_path_map", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_library_root_id"], ["library_roots.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "import_job_logs",
        sa.Column("import_job_id", sa.Integer(), nullable=False),
        sa.Column("logged_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("event", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("data", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["import_job_id"], ["import_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_job_logs_import_job_id"), "import_job_logs", ["import_job_id"], unique=False
    )
    op.create_index(
        "ix_import_job_logs_job_id_ts",
        "import_job_logs",
        ["import_job_id", "logged_at"],
        unique=False,
    )
    op.create_table(
        "import_series",
        sa.Column("import_job_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "MATCHED",
                "NO_MATCH",
                "DUPLICATE",
                "CONFIRMED",
                "SKIPPED",
                "IMPORTING",
                "IMPORTED",
                "FAILED",
                name="importseriesstatus",
            ),
            nullable=False,
        ),
        sa.Column("raw_series_name", sa.String(length=500), nullable=False),
        sa.Column("raw_year", sa.Integer(), nullable=True),
        sa.Column("raw_publisher", sa.String(length=255), nullable=True),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("sample_paths", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("source_folder", sa.String(length=1000), nullable=True),
        sa.Column("has_files", sa.Boolean(), nullable=False),
        sa.Column("cv_id", sa.Integer(), nullable=True),
        sa.Column("cv_title", sa.String(length=500), nullable=True),
        sa.Column("cv_year", sa.Integer(), nullable=True),
        sa.Column("cv_publisher", sa.String(length=255), nullable=True),
        sa.Column("cv_issue_count", sa.Integer(), nullable=True),
        sa.Column("cv_url", sa.String(length=500), nullable=True),
        sa.Column("cv_match_score", sa.Float(), nullable=True),
        sa.Column("cv_match_method", sa.String(length=50), nullable=True),
        sa.Column("user_selected_cv_id", sa.Integer(), nullable=True),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["import_job_id"], ["import_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_series_cv_id"), "import_series", ["cv_id"], unique=False)
    op.create_index(
        op.f("ix_import_series_import_job_id"), "import_series", ["import_job_id"], unique=False
    )
    op.create_index(
        "ix_import_series_job_status", "import_series", ["import_job_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_import_series_series_id"), "import_series", ["series_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_import_series_series_id"), table_name="import_series")
    op.drop_index("ix_import_series_job_status", table_name="import_series")
    op.drop_index(op.f("ix_import_series_import_job_id"), table_name="import_series")
    op.drop_index(op.f("ix_import_series_cv_id"), table_name="import_series")
    op.drop_table("import_series")
    op.drop_index("ix_import_job_logs_job_id_ts", table_name="import_job_logs")
    op.drop_index(op.f("ix_import_job_logs_import_job_id"), table_name="import_job_logs")
    op.drop_table("import_job_logs")
    op.drop_table("import_jobs")
    # ### end Alembic commands ###
