"""add download retry fields

Revision ID: e4db993bc3df
Revises: 15b90065fc36
Create Date: 2026-02-24 12:31:45.390308

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4db993bc3df"
down_revision: str | Sequence[str] | None = "15b90065fc36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "download_history",
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "download_history",
        sa.Column("max_retries", sa.Integer(), server_default="3", nullable=False),
    )
    op.add_column(
        "download_history", sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("download_history", "next_retry_at")
    op.drop_column("download_history", "max_retries")
    op.drop_column("download_history", "retry_count")
    # ### end Alembic commands ###
